#!/bin/bash
set -e

# Здесь ваши команды (выполняются от root)
echo "Настройка приложения..."

# Например, установка прав на бинарный файл
chmod +x /usr/bin/observerLm

# Или обновление кэша иконок (если вы их добавили)
update-desktop-database /usr/share/applications || true

exit 0